#!/bin/sh

# This script adds the PDF named in the first argument to the end of the PDF
# named out.pdf, and puts the result in a file named merged.pdf.

# Run me with `sh affix_to_out PATH_TO_FILE_TO_BE_ADDED`.

if ! [ -f out.pdf ]; then
    echo "No out.pdf to add to!"
    exit 1
elif [ $# -ne 1 ]; then
    echo "Too few, or too many, arguments!"
    exit 1
elif ! [ -f $1 ]; then
    echo "$1 does not exist!"
    exit 1
fi

pdftk out.pdf $1 cat output merged.pdf
