#!/bin/sh

# This code defines a scripts which installs all truetype fonts with files
# located in the same directory.

# Constants.
PATH_TO_SYSTEM_TRUETYPE_DIR="/usr/share/fonts/truetype/"

# Run script.
sudo cp *.ttf $PATH_TO_SYSTEM_TRUETYPE_DIR
